language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
sudo: required
dist: xenial

before_install:
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - chmod +x phive.phar
install:
    - ./phive.phar install
    - composer install

script:
    - ./psh code-style
    - ./psh quality
    - ./psh unit

matrix:
    allow_failures:
        - php: 7.4